version: '3'
volumes:
  next-pg-data:
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: next
      POSTGRES_PASSWORD: next
      POSTGRES_DB: next
    volumes:
      - next-pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  test-postgres:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5532:5432
