name: Build and Deploy server

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to gitea docker
        run: docker login gitea.opracs.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin <<< '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build and push Docker image
        run: |
          docker build --build-arg COMMIT_SHA=$GITHUB_SHA -t gitea.opracs.com/${{ secrets.DOCKER_USERNAME }}/fh-server:latest -t gitea.opracs.com/${{ secrets.DOCKER_USERNAME }}/fh-server:$GITHUB_SHA .
          docker push gitea.opracs.com/${{ secrets.DOCKER_USERNAME }}/fh-server --all-tags

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: build
    steps:
    - name: Set kubeconfig
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'kube.config'
        fileDir: '~/'
        encodedString: ${{ secrets.KUBE_CONFIG }}

    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.9'

    - name: Kuberentes set image
      env:
        KUBECONFIG: ~/kube.config
      run: |
        kubectl set image -n couchsurfing deployment/fh-server-app fh-server-app=gitea.opracs.com/${{ secrets.DOCKER_USERNAME }}/fh-server:$GITHUB_SHA

